CONFIG_PRINTK=y
CONFIG_LOG=y

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_STATIC_INIT_GNU=y
# CONFIG_HW_STACK_PROTECTION=y
# C++ 支持
CONFIG_CPP=y
CONFIG_HEAP_MEM_POOL_SIZE=0
# 标准库
CONFIG_NEWLIB_LIBC=y
CONFIG_REQUIRES_FULL_LIBC=y

CONFIG_USE_SEGGER_RTT=y

# enable console
CONFIG_CONSOLE=y
# CONFIG_UART_CONSOLE=y
CONFIG_RTT_CONSOLE=y

CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_CAN=y 
# CONFIG_CAN_LOOPBACK=y

# LED Strip 驱动
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_SPI=y

# SPI 驱动
CONFIG_SPI=y

CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_DMA=y
CONFIG_DMA_STM32=y
